"""create admin_action_logs table

Revision ID: f711ec857a1e
Revises: 4162e7692e74
Create Date: 2026-01-13 01:07:00.230432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f711ec857a1e'
down_revision: Union[str, Sequence[str], None] = '0dcb864f20be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('APPROVE_USER', 'REJECT_USER', 'DELETE_USER', 'SET_ROLE', name='admin_action'), nullable=False),
    sa.Column('before_role', sa.String(length=20), nullable=True),
    sa.Column('after_role', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
